# Generated by Django 2.1.7 on 2019-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190309_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defaultproduct.jpg', upload_to='profile_pics'),
        ),
    ]
